Style/HashSyntax:
  EnforcedStyle: 'ruby19'

Style/StringLiterals:
  EnforcedStyle: 'single_quotes'

Layout/CaseIndentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/GlobalVars:
  Enabled: false
